name: Terraform CI/CD

on:
  push:
    branches: [main, develop]

  pull_request:
    branches: [main, develop]

  
  # workflow_dispatch:
  #   inputs:
  #     confirm_destroy:
  #       description: 'Set to "1" to confirm destroy'
  #       required: false
  #       default: '0'
  #     confirm_prod_destroy:
  #       description: 'Set to "1" to confirm production destroy'
  #       required: false
  #       default: '0'

jobs:
  terraform-plan:
    name: "Terraform init, lint, validate and plan"
    runs-on: ubuntu-latest

    env: 
      AWS_REGION: "eu-central-1"
      TF_VERSION: "1.11.0"
      TF_WORKING_DIR: terraform/envs/test
    
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION}}

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION}}

      # - name: Install TFLint
      #   run: |
      #     curl -sLo tflint.zip 
      #     unzip tflint.zip -d /usr/local/bin
      #     tflint --version
      
      - name: Terraform init
        run: terraform init
      
      - name: Terraform validate
        run: terraform validate
      
      # - name: "TFLint"
      #   run: |
      #     tflint --init
      #     tflint
      
      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}/tfplan
          retention-days: 1
    
  deploy:
    name: Terraform Deploy
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    needs: terraform-plan
    runs-on: ubuntu-latest

    env: 
      AWS_REGION: "eu-central-1"
      TF_VERSION: "1.11.0"
      TF_WORKING_DIR: terraform/envs/test

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION}}

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION}}

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}
  
      - name: Terraform Init
        run: terraform init
  
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan